"""add ai_summart to notes

Revision ID: a4b2a9224c86
Revises: fbd2c4617366
Create Date: 2026-08-20 11:46:12.648168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b2a9224c86'
down_revision: Union[str, Sequence[str], None] = 'fbd2c4617366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'ai_summary')
    # ### end Alembic commands ###
