name: Autotests # Название нашего процесса

# 1. КОГДА ЗАПУСКАТЬ?
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# 2. ЧТО ДЕЛАТЬ?
jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      
      - name: Клонируем код репозитория
        uses: actions/checkout@v4
      
      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name:  Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
      
      - name:  Запускаем тесты
        env:
          SECRET_KEY: "supersecret_test_key_for_ci"
          DATABASE_URL: "sqlite:///./test.db"
        run: |
          pytest -v